# Generated by Django 4.0.1 on 2022-01-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('index', models.CharField(choices=[('Nifty', 'NIFTY'), ('Banknifty', 'BANKNIFTY')], default='Nifty', max_length=10)),
                ('strike_price', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10)),
                ('call_type', models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], default='CE', max_length=10)),
                ('avg_price', models.IntegerField(default=0)),
                ('sqo_price', models.IntegerField(default=0)),
                ('sqo_price2', models.IntegerField(default=0)),
                ('profit_loss', models.IntegerField(default=0)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='static-coll/charts/')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
