# Generated by Django 4.0.1 on 2022-01-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='swing_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='swing_low',
            field=models.IntegerField(default=0),
        ),
    ]
