# Generated by Django 4.0.1 on 2022-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0002_note_swing_high_note_swing_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sqo_price2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='swing_high',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='swing_low',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
