# Generated by Django 4.0.1 on 2022-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0003_alter_note_sqo_price2_alter_note_swing_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Lot',
            field=models.IntegerField(choices=[('Nifty', 'NIFTY'), ('Banknifty', 'BANKNIFTY')], default='50', max_length=9),
        ),
    ]
