# Generated by Django 4.0.1 on 2022-01-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0005_remove_note_lot_note_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lot',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('75', '75'), ('100', '100'), ('125', '125'), ('150', '150'), ('175', '175'), ('200', '200')], default='50', max_length=9),
        ),
    ]
