# Generated by Django 4.0.1 on 2022-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0008_alter_note_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
    ]
