# Generated by Django 4.0.1 on 2022-01-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0010_alter_note_lot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nse',
            new_name='NseData',
        ),
    ]
