# Generated by Django 4.0.1 on 2022-01-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0011_rename_nse_nsedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NseStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='NseData',
            new_name='NseIndexData',
        ),
    ]
